In [1]:
import pandas as pd
import sklearn
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
train=pd.read_csv('./train.csv')
test=pd.read_csv('./test.csv')

In [3]:
train.shape

(891, 12)

In [4]:
train.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [6]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# 첫번째 제출

In [2]:
train['Age'].fillna(int(train['Age'].mean()), inplace=True)

In [8]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [9]:
train['Age'].head(20)

0     22.0
1     38.0
2     26.0
3     35.0
4     35.0
5     29.0
6     54.0
7      2.0
8     27.0
9     14.0
10     4.0
11    58.0
12    20.0
13    39.0
14    14.0
15    55.0
16     2.0
17    29.0
18    31.0
19    29.0
Name: Age, dtype: float64

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [3]:
train['Sex']=train['Sex'].replace('male', 0)

In [4]:
train['Sex']=train['Sex'].replace('female', 1)

In [5]:
train['Sex'].head(10)

0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1
Name: Sex, dtype: int64

In [6]:
train['Embarked']=train['Embarked'].replace('Q',0)
train['Embarked']=train['Embarked'].replace('C',1)
train['Embarked']=train['Embarked'].replace('S',2)
train['Embarked']

0      2.0
1      1.0
2      2.0
3      2.0
4      2.0
      ... 
886    2.0
887    2.0
888    2.0
889    1.0
890    0.0
Name: Embarked, Length: 891, dtype: float64

In [7]:
train['Embarked']=train['Embarked'].fillna(1)

In [8]:
train['Cabin'].head(70)

0      NaN
1      C85
2      NaN
3     C123
4      NaN
      ... 
65     NaN
66     F33
67     NaN
68     NaN
69     NaN
Name: Cabin, Length: 70, dtype: object

In [3]:
X_train=train.drop(['PassengerId','Survived','Name','Ticket','Cabin'], axis=1)
Y_train=train['Survived']

In [38]:
model=DecisionTreeRegressor()
model.fit(X_train, Y_train)

DecisionTreeRegressor()

In [10]:
test['Sex']=test['Sex'].replace('male', 0)
test['Sex']=test['Sex'].replace('female', 1)
test['Sex']

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Sex, Length: 418, dtype: int64

In [11]:
test['Embarked']=test['Embarked'].replace('Q',0)
test['Embarked']=test['Embarked'].replace('C',1)
test['Embarked']=test['Embarked'].replace('S',2)
test['Embarked']

0      0
1      2
2      0
3      2
4      2
      ..
413    2
414    1
415    2
416    2
417    1
Name: Embarked, Length: 418, dtype: int64

In [12]:
test['Embarked']=test['Embarked'].fillna(1)

In [13]:
test['Age'].fillna(int(test['Age'].mean()), inplace=True)

In [14]:
test['Fare'].fillna(int(test['Fare'].mean()), inplace=True)

In [15]:
test_1=test.drop(['PassengerId','Name','Ticket','Cabin'], axis=1)

In [25]:
X_train.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [26]:
pred=model.predict(test_1)

In [27]:
test_1.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [28]:
sub=pd.read_csv('./submission.csv')

In [29]:
sub['Survived']=pred

In [30]:
sub.to_csv('sub.csv',index=False)

# 두번째 제출

In [40]:
model.feature_importances_

array([0.11145424, 0.31412978, 0.24433583, 0.04277106, 0.02297719,
       0.2532678 , 0.0110641 ])

In [41]:
X_train_2=X_train.drop(['Embarked'], axis=1)
test_2=test_1.drop(['Embarked'], axis=1)

In [43]:
model=DecisionTreeRegressor()
model.fit(X_train_2, Y_train)
pred=model.predict(test_2)

In [45]:
model.feature_importances_

array([0.12093668, 0.31455994, 0.23398545, 0.04682305, 0.03707105,
       0.24662382])

In [44]:
sub=pd.read_csv('./submission.csv')
sub['Survived']=pred
sub.to_csv('sub_2.csv',index=False)

# 세번째 제출

In [47]:
X_train_3=X_train.drop(['Embarked','Parch'], axis=1)
test_3=test_1.drop(['Embarked','Parch'], axis=1)

In [48]:
model=DecisionTreeRegressor()
model.fit(X_train_3, Y_train)
pred=model.predict(test_3)

In [49]:
model.feature_importances_

array([0.11018022, 0.31564608, 0.22750291, 0.05064231, 0.29602848])

In [50]:
sub=pd.read_csv('./submission.csv')
sub['Survived']=pred
sub.to_csv('sub_3.csv',index=False)

# 네번째 제출

In [16]:
X_train_4=X_train.drop(['Embarked','Parch','SibSp'], axis=1)
test_4=test_1.drop(['Embarked','Parch','SibSp'], axis=1)

In [52]:
model=DecisionTreeRegressor()
model.fit(X_train_4, Y_train)
pred=model.predict(test_4)

In [53]:
model.feature_importances_

array([0.12579812, 0.31649764, 0.24103894, 0.31666531])

In [55]:
sub=pd.read_csv('./submission.csv')
sub['Survived']=pred
sub.to_csv('sub_4.csv',index=False)

# 다섯번째 제출

In [18]:
from sklearn.ensemble import RandomForestRegressor

In [56]:
model=RandomForestRegressor(criterion='mse')
model.fit(X_train_4, Y_train)

RandomForestRegressor()

In [57]:
model.feature_importances_

array([0.11208674, 0.31029135, 0.26647562, 0.31114629])

In [60]:
pred=model.predict(test_4)

In [61]:
sub=pd.read_csv('./submission.csv')
sub['Survived']=pred
sub.to_csv('sub_5.csv',index=False)

# 여섯번째 제출

In [1]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
train=pd.read_csv('./train.csv')
test=pd.read_csv('./test.csv')

In [76]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [2]:
train['Age'].fillna(int(train['Age'].mean()), inplace=True)

In [3]:
male=[]
for i in range(len(train)):
    if train['Sex'][i]=='male':
        male.append(1)
    else:
        male.append(0)

In [4]:
train['male']=male

In [5]:
female=[]
for i in range(len(train)):
    if train['Sex'][i]=='female':
        female.append(1)
    else:
        female.append(0)
train['female']=female

In [6]:
S=[]
for i in range(len(train)):
    if train['Embarked'][i]=='S':
        S.append(1)
    else:
        S.append(0)
train['S']=S
Q=[]
for i in range(len(train)):
    if train['Embarked'][i]=='Q':
        Q.append(1)
    else:
        Q.append(0)
train['Q']=Q
C=[]
for i in range(len(train)):
    if train['Embarked'][i]=='C':
        C.append(1)
    else:
        C.append(0)
train['C']=C

In [7]:
X_train_6=train.drop(['PassengerId','Survived','Name','Ticket','Cabin','Embarked','Sex'], axis=1)
Y_train=train['Survived']

In [8]:
test['Age'].fillna(int(test['Age'].mean()), inplace=True)

In [9]:
test['Fare'].fillna(int(test['Fare'].mean()), inplace=True)

In [10]:
male=[]
for i in range(len(test)):
    if test['Sex'][i]=='male':
        male.append(1)
    else:
        male.append(0)
test['male']=male
female=[]
for i in range(len(test)):
    if test['Sex'][i]=='female':
        female.append(1)
    else:
        female.append(0)
test['female']=female

In [11]:
S=[]
for i in range(len(test)):
    if test['Embarked'][i]=='S':
        S.append(1)
    else:
        S.append(0)
test['S']=S
Q=[]
for i in range(len(test)):
    if test['Embarked'][i]=='Q':
        Q.append(1)
    else:
        Q.append(0)
test['Q']=Q
C=[]
for i in range(len(test)):
    if test['Embarked'][i]=='C':
        C.append(1)
    else:
        C.append(0)
test['C']=C

In [12]:
test_6=test.drop(['PassengerId','Name','Ticket','Cabin','Embarked','Sex'], axis=1)

In [14]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(criterion='mse')
model.fit(X_train_6, Y_train)

RandomForestRegressor()

In [15]:
model.feature_importances_

array([0.10442394, 0.24180355, 0.04689414, 0.02477015, 0.2486114 ,
       0.14977526, 0.15364263, 0.01511085, 0.00507597, 0.0098921 ])

In [16]:
pred=model.predict(test_6)

In [17]:
sub=pd.read_csv('./submission.csv')
sub['Survived']=pred
sub.to_csv('sub_6.csv',index=False)

In [59]:
X_train_6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Pclass  891 non-null    int64  
 1   Age     891 non-null    float64
 2   SibSp   891 non-null    int64  
 3   Parch   891 non-null    int64  
 4   Fare    891 non-null    float64
 5   male    891 non-null    int64  
 6   female  891 non-null    int64  
 7   S       891 non-null    int64  
 8   Q       891 non-null    int64  
 9   C       891 non-null    int64  
dtypes: float64(2), int64(8)
memory usage: 69.7 KB


# 일곱번째 제출

In [13]:
X_train_7=X_train_6.drop(['S','Q','C'], axis=1)
test_7=test_6.drop(['S','Q','C'], axis=1)

In [15]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(criterion='mse')
model.fit(X_train_7, Y_train)

RandomForestRegressor()

In [62]:
model.feature_importances_

array([0.10324528, 0.25095282, 0.0450211 , 0.0243792 , 0.26716052,
       0.13569631, 0.17354478])

In [63]:
X_train_7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Pclass  891 non-null    int64  
 1   Age     891 non-null    float64
 2   SibSp   891 non-null    int64  
 3   Parch   891 non-null    int64  
 4   Fare    891 non-null    float64
 5   male    891 non-null    int64  
 6   female  891 non-null    int64  
dtypes: float64(2), int64(5)
memory usage: 48.9 KB


In [16]:
pred=model.predict(test_7)

In [17]:
sub=pd.read_csv('./submission.csv')
sub['Survived']=pred
sub.to_csv('sub_7.csv',index=False)

# 여덟번째 제출

In [13]:
X_train_8=X_train_6.drop(['S','Q','C','SibSp','Parch'], axis=1)
test_8=test_6.drop(['S','Q','C','SibSp','Parch'], axis=1)

In [14]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(criterion='mse')
model.fit(X_train_8, Y_train)
pred=model.predict(test_8)

In [15]:
sub=pd.read_csv('./submission.csv')
sub['Survived']=pred
sub.to_csv('sub_8.csv',index=False)

# 아홉번째 제출

In [91]:
X_train_6['Pclass'] = X_train_6['Pclass'].astype('category')
X_train_9=X_train_6
X_train_9['1']=pd.get_dummies(X_train_6['Pclass'])[1]
X_train_9['2']=pd.get_dummies(X_train_6['Pclass'])[2]
X_train_9['3']=pd.get_dummies(X_train_6['Pclass'])[3]

In [92]:
X_train_9

Pclass   Age  SibSp  Parch     Fare  male  female  S  Q  C  1  2  3
0        3  22.0      1      0   7.2500     1       0  1  0  0  0  0  1
1        1  38.0      1      0  71.2833     0       1  0  0  1  1  0  0
2        3  26.0      0      0   7.9250     0       1  1  0  0  0  0  1
3        1  35.0      1      0  53.1000     0       1  1  0  0  1  0  0
4        3  35.0      0      0   8.0500     1       0  1  0  0  0  0  1
..     ...   ...    ...    ...      ...   ...     ... .. .. .. .. .. ..
886      2  27.0      0      0  13.0000     1       0  1  0  0  0  1  0
887      1  19.0      0      0  30.0000     0       1  1  0  0  1  0  0
888      3  29.0      1      2  23.4500     0       1  1  0  0  0  0  1
889      1  26.0      0      0  30.0000     1       0  0  0  1  1  0  0
890      3  32.0      0      0   7.7500     1       0  0  1  0  0  0  1

[891 rows x 13 columns]

In [93]:
test_6['Pclass'] = test_6['Pclass'].astype('category')
test_9=test_6
test_9['1']=pd.get_dummies(test_6['Pclass'])[1]
test_9['2']=pd.get_dummies(test_6['Pclass'])[2]
test_9['3']=pd.get_dummies(test_6['Pclass'])[3]

In [95]:
X_train_9.drop(['Pclass'], axis=1, inplace=True)
test_9.drop(['Pclass'], axis=1, inplace=True)

In [97]:
model=RandomForestRegressor(criterion='mse')
model.fit(X_train_9, Y_train)

RandomForestRegressor()

In [98]:
pred=model.predict(test_9)

In [99]:
sub=pd.read_csv('./submission.csv')
sub['Survived']=pred
sub.to_csv('sub_9.csv',index=False)

# 열번째 제출

In [13]:
X_train_10=X_train_6.drop(['SibSp','Parch'], axis=1)
test_10=test_6.drop(['SibSp','Parch'], axis=1)

In [14]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(criterion='mse')
model.fit(X_train_10, Y_train)
pred=model.predict(test_10)

In [15]:
sub=pd.read_csv('./submission.csv')
sub['Survived']=pred
sub.to_csv('sub_10.csv',index=False)